---
- hosts: web
  remote_user: deploy
  become: yes
  become_user: root
  become_method: sudo

  vars:
    username: 'deploy'
    home: '/home/{{ user }}'

    update_cache: yes
    cache_valid_time: 86400

    pub_ip: '84.201.144.34'

  roles:
    - aptUpdate
    - ovpn
