---
 - name: Install openvpn
   apt:
     name: openvpn
     state: present
   environment:
     RUNLEVEL: 1

 - name: Install easy-rsa
   apt:
     name: easy-rsa
     state: present
   environment:
     RUNLEVEL: 1

#- name: Create symlink
#  file: src=/usr/share/easy-rsa/openssl-1.0.0.cnf dest=/usr/share/easy-rsa/openssl.cnf state=link

 - name: Create symlink
   file: 
     src: '/usr/share/easy-rsa/{{ openssl_ver }}.cnf'
     dest: '/usr/share/easy-rsa/openssl.cnf'
     state: link

 - name: Create config from template
   template:
     src: templates/vars.j2
     dest: /usr/share/easy-rsa/vars
     owner: root
     group: root
     mode: 0644
     backup: yes

#- name: Source vars
#  shell: source vars
#  args:
#    chdir: /usr/share/easy-rsa

 - name: Source vars
   shell: |
     source vars
     exit 0
   args:
     chdir: /usr/share/easy-rsa

 - name: Building CA
   shell: ./build-ca
   args:
     chdir: /usr/share/easy-rsa
  #  creates: 

 - name: Create dir
   file: 
     path: '/etc/openvpn/keys'
     state: directory

 - name: "loop through list"
   debug:
     msg: "An item: {{item}}"
   with_items:
     - 1
     - 2
     - 3

 - name: Copy keys
#  debug:
#    msg: "--> {{ item }}"
   copy:
     src: "/usr/share/easy-rsa/keys/{{ item }}"
     dest: "/etc/openvpn/{{ item }}"
     owner: root
     group: root
     mode: 0400
     remote_src: yes
   with_items:
     - 'ca.crt'
     - 'ca.key'
     - 'vpn-server.crt'
     - 'vpn-server.key'
     - 'ta.key'
     - 'dh2048.pem'
   notify: reload openvpn

 - name: Create vpn sever config
   template:
     src: templates/server.conf.j2
     dest: /etc/openvpn/server/server.conf
     owner: root
     group: root
     mode: 0644
     backup: yes
   notify: reload openvpn

# Синтаксис автозапуска OpenVPN : systemctl enable openvpn-client@<configuration>.
#- name: Add autostart openvpn service
#  systemd:
#    name: openvpn-server@server
#    state: started
#    enabled: yes
